// config/site.config.js
export const SITE = {
  businessName: "Euro Auto House",
  tagline: "quality car care service",
  address: "3855 St Johns Parkway Sanford, FL 32771",
  audience: "Mercedes Benz , BMW , VW and Audi owners",
  heroHeadline: "Full-Service Diagnostics for Your Luxury Vehicles",
  heroCTA: "Give us a call for a free quote",
  email: "euroautohouse@gmail.com",
  phone: "(407) 279-3226",
  mapAddress: "3855 St Johns Parkway Sanford, FL 32771",
  mapLink: "https://www.google.com/maps/place/1100+Central+Park+Dr,+Sanford,+FL+32771,+USA/@28.802197,-81.317028,15z/data=!4m6!3m5!1s0x88e712f2bbb9b25b:0xb5227a87fa5c9ed3!8m2!3d28.8021966!4d-81.3170283!16s%2Fg%2F11bw3ylpw9?hl=en&entry=ttu&g_ep=EgoyMDI1MTAwNi4wIKXMDSoASAFQAw%3D%3D",
  colors: {
    primary: "#b51716",
    accent: "#fabd12",
    base: "#000000",
    contrast: "#FFFFFF",
  },
  fonts: {
    display: "Poppins ExtraBold",
    body: "Arial, Helvetica, sans-serif",
  },
  social: {
    facebook: "https://www.facebook.com/euroautohouse/",
    instagram: "https://www.instagram.com/euroautohouse/?hl=en",
  },
  keywords: [
    "european auto repair sanford fl",
    "mercedes repair sanford fl",
    "bmw service sanford fl",
    "audi mechanic sanford fl",
    "euro auto house sanford fl",
    "european car maintenance near me",
    "luxury car oil change sanford fl",
    "certified european auto technicians",
    "european vehicle diagnostics",
    "transmission repair sanford fl",
    "brake service for european cars",
    "air conditioning repair for bmw mercedes audi",
    "factory-trained mechanics",
    "ase certified auto repair sanford fl",
    "mobil 1 oil change sanford fl",
    "wheel restoration and alignment sanford",
    "auto repair near lake mary fl",
    "sanford fl european auto shop",
    "bmw mechanic near orlando fl",
    "european car repair near me",
    "euro car service seminole county fl",
    "euro auto house sanford",
    "euro auto house reviews",
    "euro auto house services",
    "euro auto house oil change",
    "european auto repair in sanford fl",
    "bmw mercedes audi specialists sanford fl",
    "european car service near orlando",
    "european car workshop sanford fl",
    "european performance repair sanford fl",
    "luxury vehicle maintenance sanford fl"
  ],
  nav: [
    { label: "Home", href: "/" },
    { label: "Services", href: "/services" },
    { label: "Gallery", href: "/gallery" },
    { label: "Interesting Facts", href: "/interesting-facts" },
    { label: "Contact", href: "/contact" }
  ],
  services: [
    { title: "Flex Services", desc: "Scheduled maintenance tailored for European vehicles, oil changes, filters, fluid flushes.", icon: "🛠️" },
    { title: "Specialized Diagnostics", desc: "Factory-grade scanning & troubleshooting for Mercedes, BMW, Audi, VW.", icon: "🔎" },
    { title: "Transmission Services", desc: "Service, repair, and replacement using OEM parts and correct specs.", icon: "⚙️" },
    { title: "Brakes & Suspension", desc: "Performance brake work, ABS diagnostics, alignments, control arms, struts.", icon: "🛞" },
    { title: "A/C & Cooling", desc: "R134a/R1234yf service, compressor & condenser replacement, coolant systems.", icon: "❄️" },
    { title: "Electrical & Programming", desc: "Module coding, battery registration, key & immobilizer programming.", icon: "⚡" }
  ]
};
